---
- name: Install DataDog Agent
  shell: DD_AGENT_MAJOR_VERSION=7 DD_API_KEY={{ datadog_api_key }} DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/install_script.sh)"
  args:
    creates: /etc/datadog-agent/datadog.yaml
